# Generated by Django 5.1.5 on 2025-01-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_alter_gamelist_game_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game", models.CharField(max_length=100)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("dev", models.CharField(blank=True, max_length=100, null=True)),
                ("publisher", models.CharField(blank=True, max_length=100, null=True)),
                ("platform", models.CharField(max_length=100)),
            ],
        ),
    ]
