# Generated by Django 5.1.5 on 2025-01-16 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="game_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_list",
                to="server.game",
            ),
        ),
    ]
