# Generated by Django 5.1.5 on 2025-01-16 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0006_alter_gamelist_game_id_alter_gamelist_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamelist",
            old_name="game_id",
            new_name="game",
        ),
    ]
