# Generated by Django 5.1.5 on 2025-01-17 23:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0007_rename_game_id_gamelist_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="played_time",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
