# Generated by Django 5.1.5 on 2025-01-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0008_alter_gamelist_played_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamelist",
            name="game_state",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("playing", "playing"),
                    ("finished", "finished"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
    ]
